# Generated by Django 3.2.4 on 2021-06-24 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 17, 16, 39, 542321, tzinfo=utc)),
        ),
    ]
